openapi: 3.0.3
info:
  title: Cornerstone
  version: 1.0.0
servers:
  - url: https://apicompanion-dev.bytequest.solutions/api/v1
tags:
  - name: Signup and Login
    description: Authentication Management
  - name: Google Authentication
    description: Google Authentication Management
  - name: Password
    description: Password Reset Management
  - name: Users
    description: User Management
paths:
  /auth/register:
    post:
      tags:
        - Signup and Login
      operationId: Signup
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
                - email
                - password
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  example: John.Doe@gmail.com
                password:
                  type: string
                  example: $1234abcd
      responses:
        "200":
          description: Registered Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /auth/login:
    post:
      tags:
        - Signup and Login
      operationId: Login
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
                - password
              type: object
              properties:
                email:
                  type: string
                  example: John.Doe@gmail.com
                password:
                  type: string
                  example: $1234abcd
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Login"
                  message:
                    type: string

  /auth/google:
    get:
      tags:
        - Google Authentication
      operationId: Google Redirect URL
      description: Redirect to the Google Login Page
      responses:
        "200":
          description: Successful Operation
    post:
      tags:
        - Google Authentication
      operationId: Google Signup or Login
      description: Google Signup or Login
      requestBody:
        content:
          application/json:
            schema:
              required:
                - code
              type: object
              properties:
                code:
                  type: string
                  example: 4/0AeaYSHCoSLQlzCvmwNfx_purqgyrLWJ2l2JvhmpRW9-amog1Suymw6HL64lKDfOYadviPg
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Login"
                  message:
                    type: string

  /auth/forget-password:
    post:
      tags:
        - Password
      operationId: Forget Password
      description: Send a Password Reset Link to Provided Email
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
              type: object
              properties:
                email:
                  type: string
                  example: John.Doe@gmail.com
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /auth/reset-password:
    post:
      tags:
        - Password
      operationId: Reset Password
      description: Changes the Password of the User Who Requested to Reset the Password
      requestBody:
        content:
          application/json:
            schema:
              required:
                - token
                - password
              type: object
              properties:
                token:
                  type: string
                  example: 1I69UCa0BxqtIYVx23Lc
                password:
                  type: string
                  example: $1234abcd
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /auth/validate-token:
    post:
      tags:
        - Password
      operationId: Validate Token
      description: Validates the token from forget password email
      requestBody:
        content:
          application/json:
            schema:
              required:
                - token
              type: object
              properties:
                token:
                  type: string
                  example: 1234
      responses:
        '200':
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array

  /users/profile:
    get:
      tags:
        - Users
      operationId: User Profile
      description: User's All Information
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/Profile"
    post:
      tags:
        - Users
      operationId: Update User Profile
      description: Update User's Email and Name
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              required:
                - email
                - name
              type: object
              properties:
                email:
                  type: string
                  example: John.Doe@gmail.com
                name:
                  type: string
                  example: "John Doe"
      responses:
        "200":
          description: Successful Operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Login:
      type: array
      items:
        type: object
        properties:
          accessToken:
            type: string
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImhzYW1pZC5hYWgwQGdtYWlsLmNvbSIsIklEIjoiMGFmMTI5ODMtODMzZS00ZDQ0LWJkMzAtNDczOWUyZjBjYmYyIiwiZXhwIjoxNzA5NDY3NjM2LCJpYXQiOjE3MDk0NjA0MzYsImlzcyI6Im1vaGFtbWFkIn0.eU6UyDmdVlIWnuOVQyLi8iVci6WQFa1Tjxl7FMEcQ2U
    Profile:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
            example: some-generated-uuid
          name:
            type: string
            example: John Doe
          email:
            type: string
            example: John.Doe@gmail.com
          createdAt:
            type: string
            example: "2024-03-24 05:09:30.709 +0330 +0330"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
